# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170508_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'In Progress'), (2, 'Postponed'), (3, 'Deferred'), (4, 'Hope to Revisit'), (5, 'Abandoned')], default=0),
            preserve_default=False,
        ),
    ]
