# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='icon',
            field=models.CharField(default='leaf', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default='leaf', max_length=32),
            preserve_default=False,
        ),
    ]
