# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='RotatingTask',
            new_name='Task',
        ),
        migrations.AddField(
            model_name='taskcollection',
            name='tasks',
            field=models.ManyToManyField(to='api.Task'),
        ),
    ]
