# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170418_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcollection',
            name='identifier',
            field=models.CharField(default='donger', max_length=8),
            preserve_default=False,
        ),
    ]
