# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170428_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCache',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
            ],
        ),
    ]
